### ISSUE TITLE
Python 3 Version ?

### ISSUE THREAD

**Issue by Minege** [mindcat/MulticraftApi#2]
Hey yo,

are you able to create a python 3 version of the api ?

**Comment by ItsEternity** [comment]
https://gist.github.com/ItsEternity/6129c36596fbe998df5d7efe8e37e76f

I created this using a converting from Python 2 to Python 3, should work.

**Comment by Minege** [comment]
Hey, thank you man :) !

2016-09-08 21:21 GMT+02:00 ItsEternity <notifications@github.com>:

**Comment by ItsEternity** [comment]
Could you test and tell me if it does work?

**Comment by Minege** [comment]
Hi, i need to go now :\

I will test tomorrow in the afternoon.

Thank for the email, anyway!

2016-09-08 21:30 GMT+02:00 ItsEternity <notifications@github.com>:

**Comment by mindcat** [comment]
Sorry about the late. I have no plan to do Python3 version, Pull requests is welcome :D

**Comment by Minege** [comment]
Hi, i'm sorry too.

I didn't built the Python 3 Version.

I actually use the PHP Api, cause it's a lot more convenient.

Thank !



2016-10-02 22:18 GMT+02:00 mindcat <notifications@github.com>:

**Comment by mindcat** [comment]
Okay :D
